# Generated by Django 5.2.8 on 2025-11-26 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1f77b4', help_text='Color en formato HEX (ej: #1f77b4)', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('year_inicio', models.IntegerField(help_text='Ej: -1513 = 1513 a.C., 2024 = 2024 d.C.', verbose_name='Año inicio')),
                ('month_inicio', models.PositiveSmallIntegerField(blank=True, help_text='1-12 (opcional)', null=True, verbose_name='Mes inicio')),
                ('day_inicio', models.PositiveSmallIntegerField(blank=True, help_text='1-31 (opcional)', null=True, verbose_name='Día inicio')),
                ('year_fin', models.IntegerField(blank=True, null=True, verbose_name='Año fin')),
                ('month_fin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes fin')),
                ('day_fin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día fin')),
                ('color', models.CharField(default='#1f77b4', help_text='Color del evento (por defecto usa el de la categoría)', max_length=20)),
                ('imagen', models.URLField(blank=True, help_text='URL opcional de una imagen relacionada', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='lineatiempo.categoria')),
            ],
            options={
                'ordering': ['year_inicio', 'month_inicio', 'day_inicio'],
            },
        ),
    ]
